name: Go CI/CD

on:
  push:
    branches:
      - master
      - feature/devops-ci-pipe

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.1

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o /go/bin/app .

      - name: Test
        run: go test ./...

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...

      - name: Security Scan
        run: |
          go get -u github.com/securego/gosec/cmd/gosec
          gosec -exclude=G104 ./...