name: Go CI/CD

on:
  push:
    branches: [master, feature/devops-ci-pipe]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.1

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o ./app .

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Install gosec
        run: go get -u github.com/securego/gosec/cmd/gosec

      - name: Run gosec
        run: gosec -exclude=G104 ./...

      - name: Install nancy
        run: go get -u github.com/sonatype-nexus-community/nancy

      - name: Run nancy
        run: nancy ./go.mod

      - name: Test
        run: go test ./...