name: Go CI/CD

on:
  push:
    branches: [master, feature/devops-ci-pipe]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.1

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o ./app .

      - name: Test
        run: go test ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Security Scan
        run: |
          go get -u github.com/securego/gosec/cmd/gosec
          gosec -exclude=G104 ./...